### ISSUE TITLE
[Tutorial] sample of ExperimentModule for using ae.py?

### ISSUE THREAD

**Issue by Thanh-Binh** [ctrl-z-9000-times/sdr_algorithms#2]
Can you give me a very simple sample of ExperimentModule for testing?

**Comment by D-McDougall** [comment]
Yes!

See files: ae.py and func_tests/mnist_sp.py
Also see: `pydoc3 ae` - as I did write some documentation for this.

Notice mnist_sp.py lines 148 - 158: these are the default parameters.  The "ae" module imports "mnist_sp" module and reads these parameters.   The AE module can change these parameters and then pass them to  mnist_sp's main function for testing, and the main function returns the resulting score.

Start by running: `python3 ./ae.py --parse ./func_tests/mnist_sp.py`
This should create the folder:  `func_tests/mnist_sp_ae/`
Which should contain the file `lab_report.txt`
Open the lab report.  The lab report has sections which are delineated by 80 "=" signs.  The very first section is never modified by the program so you can keep your notes there.  The next section should contain the default parameters.

Now lets run the default parameters: `python3 ./ae.py -n 4 --default_parameters ./func_tests/mnist_sp.py`
Where -n 4 is the number of concurrent processes to use, by default this uses as processes as there are CPU cores.
Reload & watch the lab_report file until you see that it has more than 0 attempts, like this:
```
================================================================================
Default Parameters
Hash: DFF7ECA4
Journel: ./func_tests/mnist_sp_ae/DFF7ECA4.journel
Attempts: 4     <<<--- It finish evaluating this many times!
Scores: 0.9531, 0.9528, 0.9533, 0.9537
Mean & Standard Deviation: 0.953225 & 0.000326917
P-Value: 1
Notes:     FYI you can put your notes on & after this line and
the program will not parse them or change them.
```

**Comment by D-McDougall** [comment]
Next let's run an experiment.  Let's change the number of mini_columns from 100 to 150 and see what happens.  First stop the program and open the lab_report file.  **Don't edit the lab-report while the program is running!  Stuff will get overwritten and lost!**  

In the lab report, use copy-paste to append the following new section to the end of the file:
```
================================================================================
Modification: ['mini_columns'] = 150
```
Save it and run: `$ ./ae.py --parse ./mnist_sp.py`
The parse option tells the "AE" program to read the lab report, write it back to file, and do nothing else.  
Now re-open the lab-report file and the section you added should be all filled in like:
```
================================================================================
Modification: ['mini_columns'] = 150
Hash: C302F3F4
Journel: ./func_tests/mnist_sp_ae/C302F3F4.journel  <<-- Program run logs live here.
Attempts: 0
Scores: 
P-Value: nan
Notes: 
```
The HASH value is important, it is the ID for this parameter set.  To run these parameters call:
`$ ./ae.py -n 4 --hashes C302F3F4 ./mnist_sp.py`

After you've run the modified parameters a few times, look at the table in the third section of the lab-report.  It should look something like (I changed a different parameter actually):
```
================================================================================
    Hash |   N |      Score |   P-Value | Modifications
37340A86 |  24 |   0.953846 |     0.238 | ['active_thresh'] = 16
DFF7ECA4 |   4 |   0.953225 |         1 | Default Parameters
```
Where the columns mean:
*  N is the number of times the experiment was run.
* Score is the average score
* P-Value is the probability that the difference in score between the default-parameters and the current row is not caused by the modified parameters, but rather by chance.
   - All P-Values are based on the default parameters, as listed in the source file.  If/when they change you may be prompted to update the lab-report.

**Comment by D-McDougall** [comment]
Notes:
The HASH value includes the command line invocation of the program, so if you changing the flags then AE should keep the results separate.  

I wrote this program to automate my workflow, and its not yet fully automated.  There are features incomplete and missing.  For the time being I am not actively using or developing this program.

I hope this tutorial helps you @Thanh-Binh !

**Comment by Thanh-Binh** [comment]
@ctrl-z-9000-times thanks for your tutorial..
I run it, but have an error:
$ python3 ./ae.py --parse ./func_tests/mnist_sp.py
Memory Limit 6.9 GB per instance.
Traceback (most recent call last):
  File "./ae.py", line 833, in <module>
    ae = LabReport(args.experiment, None, args.tag)
  File "./ae.py", line 334, in __init__
    self.load_experiment_module(experiment_argv[0])
  File "./ae.py", line 377, in load_experiment_module
    exec(self.module_reload, exec_globals)
  File "<string>", line 1, in <module>
  File "./func_tests/mnist_sp.py", line 22, in <module>
    from spatial_pooler import SpatialPooler
  File "/home/binh/experiments/sdr_algorithms/spatial_pooler.py", line 5, in <module>
    from synapses import SynapseManager
ModuleNotFoundError: No module named 'synapses'

Can you send me "synapses" package? Thanks

**Comment by D-McDougall** [comment]
You need to compile it.  It is a Cython module (Cython needs to be installed).  Source is at "synapses.pyx"
The command to build it should be:
`$ ./setup.py build_ext --build-lib`

Edit: IIRC: this might leave the compiled python module in the wrong place so you may need to move it, or try:
```
$ ./setup.py build_ext --build-lib `pwd`/../
```

**Comment by Thanh-Binh** [comment]
thanks
